big-o-notation - Roland Estropia Jr.
restropiajr/c0523-code-solutions pull request #72
Opened 2023-06-21 00:27 UTC by restropiajr

2023-06-26 16:57 UTC, shawnkost requested changes
Some changes requested here Roland!

2023-06-26 16:57 UTC, shawnkost commented on big-o-notation/big-o.js
> +      unique[unique.length] = word; // 3 * n = O(3n)
You want to drop all the coefficients, so it's just `O(n)`

2023-06-26 16:57 UTC, shawnkost commented on big-o-notation/big-o.js
> +      let c = 0; // 1 * n = O(1n)
All just `O(n)`

2023-06-26 16:57 UTC, shawnkost commented on big-o-notation/big-o.js
> +        isUnique = false; // 1 * n * n = O(1n^2)
All just `O(n^2)`

2023-06-26 16:57 UTC, shawnkost commented on big-o-notation/big-o.js
> +      // 1 * n = O(1n)
Should just be `O(n)`

2023-06-26 16:57 UTC, shawnkost commented on big-o-notation/big-o.js
> +      unique[unique.length] = word; // 3 * n = O(3n))
Should be `O(n)`

2023-06-29 17:31 UTC, TimelikeClosure approved these changes

2023-06-29 18:23 UTC, merged